### ISSUE TITLE
Server disconnected error

### ISSUE THREAD

**Issue by Noglen** [Bre77/advantage_air#2]
If I try to send 2 commands, one immediately after the other, I get a "Server Disconnected" error.

I get this from Home Assistant if I try to (say) turn on 2 zones with a single service call, and I was able to reproduce it by simply calling async_change twice as per below

```
    async with aiohttp.ClientSession() as session:
        api = advantage_air("x.x.x.x", 2025, session, 5)
    
        await api.async_change({"ac1": {"zones": {"z04": {"state": "open"}}}})
        await api.async_change({"ac1": {"zones": {"z05": {"state": "open"}}}})
```

Weirdly, if I add `await asyncio.sleep(0)` before calling `self.session.get` call it then works correctly  (I originally tried an actualy delay, but even using 0 seems to fix the problem - sorry i'm not really a python dev so can't really explain why).

**Comment by Bre77** [comment]
Interesting issue. The asyncio.Lock() is meant to prevent two actions from actually happening at once, but something must be happening in the loop. I might take your await asyncio.sleep(0) suggestion but instead place it at the end of the loop to basically give the system some time to actually make the change.

Out of interest what type of system are you running? All my testing is with an e-zone system.

**Comment by Bre77** [comment]
Also just want too confirm I can directly reproduce this error on my system. I will get this fixed and bump the dependency in Home Assistant.

`aiohttp.client_exceptions.ServerDisconnectedError`

**Comment by Noglen** [comment]
Nice, thanks for the quick reply.

I've got a MyAir5 with temperature sensors on all the zones (had it installed a couple of months ago).  Not sure if there are any differences compared with the e-zone, but feel free to hit me up if you need anything tested on a different sytem.

**Comment by Bre77** [comment]
I have pushed a change to this repo that handles the two errors that can occur with this issue. I expect this is related to how the Advantage Air app doesn't actually use a "real" web server and isn't handling the persistent connections correctly. I'll need to test this a bit more before pushing it to pypy and Home Assistant, as I suspect I may have introduced a potential endless error loop.

**Comment by Bre77** [comment]
I believe this issue is resolved by https://pypi.org/project/advantage-air/0.2.5/
The issue in Home Assistant will be resolved by https://github.com/home-assistant/core/pull/52813
